#!/bin/bash

set -e
set -u
DD=$ESS_DATA_DIR/GriffDataRead

ess_griffanautils_extractevts $DD/10evts_singleneutron_on_b10_reduced.griff out.griff 5 999
ess_griffanautils_extractevts $DD/10evts_singleneutron_on_b10_reduced.griff out.griff 5
ess_griffanautils_extractevts $DD/10evts_singleneutron_on_b10_reduced.griff out.griff 9

for m in reduced full minimal; do
    f=$DD/10evts_singleneutron_on_b10_${m}.griff
    ess_griffanautils_extractevts $f out.griff 0 1 2 3 4 5 6 7 8 9
    diff $f out.griff
    ess_griffanautils_extractevts $f out.griff 0 7
    ess_griffformat_dumpfile out.griff
    ess_griffformat_info out.griff
done


