#!/usr/bin/env bash

#A bit hackish, but we basically want to compile mcpl without zlib support:

CC=`python -c 'import os;import pickle;import simplebuild.cfg as cfg;print(pickle.load(open(cfg.dirs.envcache,"rb"))["system"]["volatile"]["c"]["compiler"])'`
if [ $? != 0 ]; then
    exit 1
fi
P=$(python3 -c "import simplebuild.cfg as c; print(c.pkgs['MCPL']['dirname'])")
$CC $P/libsrc/mcpl.c -std=c99 -DMCPL_HEADER_INCPATH='"MCPL/mcpl.h"' -I$SBLD_INCLUDE_DIR $P/app_tool/main.c -lm -o mcpl_tool_nogz && \
MCPLTESTS_TESTTOOL=./mcpl_tool_nogz sb_mcpltestsfmt2_testtool
