#!/usr/bin/env bash
set -e
set -o pipefail
ess_g4utils_g4logsanitiser ess_g4tests_datacollect -m MINIMAL -o testoutput_minimal.griff -n 50 |grep -v 'G4Launcher:: Begin simulation of event'
ess_griffformat_info testoutput_minimal.griff |grep -v 'Total \['

