#!/usr/bin/env bash
set -e
set -o pipefail
ess_g4utils_g4logsanitiser ess_g4tests_datacollect -m FULL -o testoutput_full.griff -n 10 |grep -v 'G4Launcher:: Begin simulation of event'
ess_griffformat_info testoutput_full.griff |grep -v 'Total \['

