#!/usr/bin/env bash
set -e
set -o pipefail
ess_g4utils_g4logsanitiser ess_g4tests_datacollect --filter -m REDUCED -o testoutput_reduced_filtered.griff -n 15|grep -v 'G4Launcher:: Begin simulation of event'
ess_griffformat_info testoutput_reduced_filtered.griff |grep -v 'Total \['

