#!/usr/bin/env bash
#launch geant4 job through python and dump output in custom file format. Then dump the resulting file.
ess_g4tests_datacollect -m MINIMAL -o testoutput_minimal.griff -n 50 |grep -v 'G4Launcher:: Begin simulation of event'| grep -v '/G4NDL4.'
EC=$?
if [ $EC != 0 ]; then
    exit $EC
fi
ess_griffformat_info testoutput_minimal.griff |grep -v 'Total \['

#NB: 'grep -v /G4NDL4.' is a workaround to block an annoying printout of an absolute path
#somewhere in geant4 which results in false positives in our tests

