#!/usr/bin/env bash
ess_generatorexamples_custompygen_inline -lESS_Empty|grep G4Launcher|grep -v '\[seed .*\]'
if [ ${PIPESTATUS[0]} != 0 ]; then
    exit 1
fi
ess_generatorexamples_custompygen_module -lESS_Empty|grep G4Launcher|grep -v '\[seed .*\]'
if [ ${PIPESTATUS[0]} != 0 ]; then
    exit 1
fi
