#!/usr/bin/env bash

#Unit test which makes a very simple test of our geometry, simulation and
#analysis (using an empty physics list for speed). To avoid false positives, it
#silently doesn't do anything when the Geant4 framework is not present.

if [ -d $SBLD_INSTALL_PREFIX/include/G4Launcher/ ]; then
   ess_skeletonsp_sim -t -lESS_Empty && \
   ess_skeletonsp_simanachain rundir --cleanup -n1 -lESS_Empty
fi

