name: Call test workflow

on:
  push:
  workflow_dispatch:

jobs:
  use-test-workflow:
    uses: mctools/dgcode_actions/.github/workflows/run_tests.yml@main
    with:
      pkg-repo: mctools/dgcode_val
      pkg-repo-branch: '${{ github.ref_name }}'
      dgcode-branch: main
      platform-choice: all